### ISSUE TITLE
bug with clerkClient.users.getOrganizationMembershipList()

### ISSUE THREAD

**Issue by seaniod** [wobsoriano/h3-clerk#17]
It seems that clerkClient.users.getOrganizationMembershipList() doesn't work.

Within a Nuxt/server/middleware file the following code works fine, indicating that the clerk middleware is initialised:

import {clerkClient, getAuth} from "h3-clerk"; // VERSION 0.4.8
 const user = await await clerkClient.users.getUser(userId);
 log(`user: ${user.firstName}`);
 
The user first name is correct, indicating that the userID is correct. But the next line causes an error:

await clerkClient.users.getOrganizationMembershipList(userId)

Here's the error:

 ERROR  [nuxt] [request error] [unhandled] [500] A valid resource ID is required.
  at UserAPI.requireId (./node_modules/.pnpm/@clerk+backend@1.3.0_react@18.3.1/node_modules/@clerk/backend/src/api/endpoints/AbstractApi.ts:8:13)
  at UserAPI.getOrganizationMembershipList (./node_modules/.pnpm/@clerk+backend@1.3.0_react@18.3.1/node_modules/@clerk/backend/src/api/endpoints/UserApi.ts:216:10)
  at Object.handler (./server/middleware/protect.js:28:1)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async ./node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:1975:19
  at async Object.callAsync (./node_modules/.pnpm/unctx@2.3.1/node_modules/unctx/dist/index.mjs:72:16)
  at async toNodeHandle (./node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:2266:7)
  at async ufetch (./node_modules/.pnpm/unenv@1.9.0/node_modules/unenv/runtime/fetch/index.mjs:9:17)
  at async $fetchRaw2 (./node_modules/.pnpm/ofetch@1.3.4/node_modules/ofetch/dist/shared/ofetch.37386b05.mjs:222:26)
  at async $fetch2 (./node_modules/.pnpm/ofetch@1.3.4/node_modules/ofetch/dist/shared/ofetch.37386b05.mjs:268:15)

**Comment by wobsoriano** [comment]
Are you passing an object instead? Check the usage [here](https://clerk.com/docs/references/backend/user/get-organization-membership-list#examples).

```ts
await clerkClient.users.getOrganizationMembershipList({ userId })
```

**Comment by seaniod** [comment]
Ah, yes! Sorry for raising false bug. Ironically I had seen ({userId}, tested it, but couldn't get it working either, until you pointed out that's how it's supposed to be. Thanks Robert!

**Comment by wobsoriano** [comment]
No problem! Feel free to reopen if needed 🫡
